-- SEC Filings Analysis Database Schema
-- This script creates all necessary tables for the SEC filing analysis system

-- Table: companies
-- Stores information about tracked companies
CREATE TABLE IF NOT EXISTS companies (
    id SERIAL PRIMARY KEY,
    ticker VARCHAR(10) UNIQUE NOT NULL,
    cik VARCHAR(10) UNIQUE NOT NULL,
    company_name VARCHAR(255) NOT NULL,
    sic VARCHAR(10),
    sic_description VARCHAR(255),
    state_of_incorporation VARCHAR(2),
    fiscal_year_end VARCHAR(4),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table: filings
-- Stores metadata about SEC filings
CREATE TABLE IF NOT EXISTS filings (
    id SERIAL PRIMARY KEY,
    company_id INTEGER REFERENCES companies(id) ON DELETE CASCADE,
    cik VARCHAR(10) NOT NULL,
    filing_type VARCHAR(20) NOT NULL,
    filing_date DATE NOT NULL,
    accession_number VARCHAR(25) UNIQUE NOT NULL,
    primary_document VARCHAR(255),
    primary_doc_description TEXT,
    file_url TEXT,
    local_path TEXT,
    downloaded BOOLEAN DEFAULT FALSE,
    processed BOOLEAN DEFAULT FALSE,
    download_date TIMESTAMP,
    process_date TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table: chunks
-- Stores processed document chunks for large filings
CREATE TABLE IF NOT EXISTS chunks (
    id SERIAL PRIMARY KEY,
    filing_id INTEGER REFERENCES filings(id) ON DELETE CASCADE,
    section_name VARCHAR(100),
    chunk_index INTEGER NOT NULL,
    content TEXT NOT NULL,
    token_count INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table: extracted_metrics
-- Stores financial and operational metrics extracted from filings
CREATE TABLE IF NOT EXISTS extracted_metrics (
    id SERIAL PRIMARY KEY,
    filing_id INTEGER REFERENCES filings(id) ON DELETE CASCADE,
    metric_name VARCHAR(100) NOT NULL,
    metric_value DECIMAL(20, 4),
    metric_unit VARCHAR(50),
    metric_period VARCHAR(50),
    section_name VARCHAR(100),
    extraction_confidence DECIMAL(3, 2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table: risk_factors
-- Stores risk factors and changes between filings
CREATE TABLE IF NOT EXISTS risk_factors (
    id SERIAL PRIMARY KEY,
    filing_id INTEGER REFERENCES filings(id) ON DELETE CASCADE,
    risk_category VARCHAR(100),
    risk_description TEXT NOT NULL,
    change_type VARCHAR(20), -- 'new', 'removed', 'modified', 'unchanged'
    materiality VARCHAR(20), -- 'high', 'medium', 'low'
    previous_filing_id INTEGER REFERENCES filings(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table: forward_statements
-- Stores forward-looking statements and guidance
CREATE TABLE IF NOT EXISTS forward_statements (
    id SERIAL PRIMARY KEY,
    filing_id INTEGER REFERENCES filings(id) ON DELETE CASCADE,
    statement_category VARCHAR(100), -- 'production_guidance', 'capex', 'debt_reduction', etc.
    statement_text TEXT NOT NULL,
    timeframe VARCHAR(50),
    confidence_level VARCHAR(20), -- 'high', 'medium', 'low'
    quantitative_value DECIMAL(20, 4),
    value_unit VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table: intelligence_reports
-- Stores final analysis reports generated by Claude
CREATE TABLE IF NOT EXISTS intelligence_reports (
    id SERIAL PRIMARY KEY,
    filing_id INTEGER REFERENCES filings(id) ON DELETE CASCADE,
    executive_summary TEXT,
    key_insights JSONB,
    financial_analysis TEXT,
    operational_analysis TEXT,
    strategic_assessment TEXT,
    risks_opportunities TEXT,
    peer_comparison TEXT,
    actionable_takeaways TEXT,
    full_report_html TEXT,
    materiality VARCHAR(20), -- 'high', 'medium', 'low'
    urgency VARCHAR(20), -- 'immediate', 'standard', 'low'
    report_delivered BOOLEAN DEFAULT FALSE,
    delivery_date TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for better query performance
CREATE INDEX idx_filings_company_id ON filings(company_id);
CREATE INDEX idx_filings_filing_type ON filings(filing_type);
CREATE INDEX idx_filings_filing_date ON filings(filing_date);
CREATE INDEX idx_filings_cik ON filings(cik);
CREATE INDEX idx_filings_accession ON filings(accession_number);
CREATE INDEX idx_chunks_filing_id ON chunks(filing_id);
CREATE INDEX idx_extracted_metrics_filing_id ON extracted_metrics(filing_id);
CREATE INDEX idx_risk_factors_filing_id ON risk_factors(filing_id);
CREATE INDEX idx_forward_statements_filing_id ON forward_statements(filing_id);
CREATE INDEX idx_intelligence_reports_filing_id ON intelligence_reports(filing_id);

-- Insert EQT Corporation as first company
INSERT INTO companies (ticker, cik, company_name, sic, sic_description, state_of_incorporation, fiscal_year_end)
VALUES ('EQT', '0000033213', 'EQT Corp', '1311', 'Crude Petroleum & Natural Gas', 'PA', '1231')
ON CONFLICT (ticker) DO NOTHING;

-- Grant all privileges to sec_user
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO sec_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO sec_user;
